name: Build Electron App For Win/Mac
on:
  push:
    branches:
      - main

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [windows-2019, macos-10.15]

    # create steps
    steps:
      # step1: check out repository
      - name: 仓库切换
        uses: actions/checkout@v2

      # step2: install node env
      - name: Node,yarn下载
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 配置淘宝镜像
      - name: 淘宝镜像配置
        run: |
          npm config set registry https://registry.npm.taobao.org && npm config set electron_mirror https://npm.taobao.org/mirrors/electron/

      # 安装依赖
      - name: 依赖安装
        run: |
          npm install

      # 打包构建
      - name: 打包构建
        run: |
          npm run release
        env:
          GH_TOKEN: ${{ secrets.shuhongxie }}

      # step5: cleanup artifacts in dist_electron
      - name: cleanup artifacts
        run: |
          npx rimraf "release/!(*.exe|*.dmg)"

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: release

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'release/**'
        env:
          GITHUB_TOKEN: ${{ secrets.shuhongxie }}
