name: Build Electron App For Win/Mac
on:
  push:
    tags:
      - 'v*.*.*'

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: app构建

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, windows-2019]

    # create steps
    steps:
      # step1: check out repository
      - name: 仓库切换
        uses: actions/checkout@v2

      # step2: install node env
      - name: Node,yarn下载
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 配置淘宝镜像
      - name: 淘宝镜像配置
        run: |
          npm config set registry https://registry.npm.taobao.org/
          npm config set electron_mirror https://npm.taobao.org/mirrors/electron/
          npm config set electron_builder_binaries_mirror https://npm.taobao.org/mirrors/electron-builder-binaries/
          npm config ls

      # 安装依赖
      - name: 依赖安装
        run: |
          npm i

      - name: 打包构建
        run: |
          npm run build
        env:
          GH_TOKEN: ${{ secrets.shuhongxie }}

      - name: window-2019下去除exe外的所有东西，准备上传
        if: matrix.os == 'windows-2019'
        run: |
          npx rimraf "release/!(*.exe)"

      - name: macos-11下去除dmg外的所有东西，准备上传
        if: matrix.os == 'macos-11'
        run: |
          npx rimraf "release/!(*.dmg)"

      - name: 安装包上传
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: release

      - name: 发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'release/**'
        env:
          GITHUB_TOKEN: ${{ secrets.shuhongxie }}
