name: Build Electron App For Win/Mac
on:
  push:
    branches:
      - main

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: app构建

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]

    # create steps
    steps:
      # step1: check out repository
      - name: 仓库切换
        uses: actions/checkout@v2

      # step2: install node env
      - name: Node,yarn下载
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 配置淘宝镜像
      - name: 淘宝镜像配置
        run: |
          npm config set registry https://registry.npm.taobao.org/ && npm config set electron_mirror https://npm.taobao.org/mirrors/electron/ && npm config set electron_builder_binaries_mirror https://mirrors.huaweicloud.com/electron-builder-binaries/

      # 安装依赖
      - name: 依赖安装
        run: |
          npm i
